# https://cwiki.apache.org/confluence/display/INFRA/Git+-+.asf.yaml+features

github:
  description: "Apache Pekko Projections is intended for building systems with the CQRS pattern, and facilitate in event-based service-to-service communication."
  homepage: https://pekko.apache.org/
  labels:
    - pekko
  
  features:
    # Enable wiki for documentation
    wiki: false
    # Enable issue management
    issues: true
    # Enable projects for project management boards
    projects: false

  enabled_merge_buttons:
    squash:  true
    merge:   false
    rebase:  true

  required_pull_request_reviews:
    dismiss_stale_reviews: false
    require_code_owner_reviews: false
    required_approving_review_count: 1

  protected_branches:
    main: { }

notifications:
  commits:              commits@pekko.apache.org
  issues:               notifications@pekko.apache.org
  pullrequests:         notifications@pekko.apache.org
  discussions:          notifications@pekko.apache.org
