name: Scalafmt

permissions: {}

on:
  pull_request:
    branches: ['**']

jobs:
  build:
    name: Code is formatted
    runs-on: ubuntu-latest
    if: github.repository == 'apache/incubator-pekko-projection'
    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          persist-credentials: false

      - name: Check project is formatted
        uses: jrouly/scalafmt-native-action@v2
        with:
          version: '3.7.11'
          arguments: '--list --mode diff-ref=origin/main'
