name: Headers

on:
  pull_request:

permissions: {}

jobs:
  check-headers:
    name: Check headers
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Cache Coursier cache
        uses: coursier/cache-action@v6.4.0

      - name: Check headers
        run: |-
          sbt \
          -Dsbt.override.build.repos=false \
          -Dsbt.log.noformat=false \
          +headerCheckAll
