name: Integration Tests for JDBC

on:
  pull_request:
  push:
    branches:
      - master
    tags-ignore: [ v.* ]

jobs:
  test:
    name: Build and Test Integration for JDBC
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - { java-version: 8,  scala-version: 2.13.11,  sbt-opts: '' }
          - { java-version: 11, scala-version: 2.13.11,  sbt-opts: '-J-XX:+UnlockExperimentalVMOptions -J-XX:+UseJVMCICompiler' }
          - { java-version: 8,  scala-version: 2.12.18,  sbt-opts: '' }
          - { java-version: 11, scala-version: 2.12.18,  sbt-opts: '-J-XX:+UnlockExperimentalVMOptions -J-XX:+UseJVMCICompiler' }
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checkout GitHub merge
        if: github.event.pull_request
        run: |-
          git fetch origin pull/${{ github.event.pull_request.number }}/merge:scratch
          git checkout scratch

      - name: Copy license acceptance
        run: |-
          cp container-license-acceptance.txt jdbc/src/it/resources/container-license-acceptance.txt

      - name: Setup JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: temurin

      - name: Cache Coursier cache
        uses: coursier/cache-action@v6.4.0        

      - name: Run all integration tests with Scala ${{ matrix.scala-version }} and Java ${{ matrix.java-version }}
        run: sbt "++${{ matrix.scala-version }} jdbc/it:test" ${{ matrix.sbt-opts }}
        env: # Disable Ryuk resource reaper since we always spin up fresh VMs
          TESTCONTAINERS_RYUK_DISABLED: true

      - name: Print logs on failure
        if: ${{ failure() }}
        run: find . -name "*.log" -exec ./scripts/cat-log.sh {} \;